name: EcoEgg
main: jp.minecraftuser.ecoegg.EcoEgg
version: ${project.version}
api-version: 1.13
depend: [EcoFramework]
commands:
  ece:
    description: ecoegg command.
    usage: /<command> xxx